hydra:
  job_logging:
#    formatters:
#      simple:
#        format: '[]'
    root:
      handlers: [file]  # logging to file only.

# model parameters
n_classes: 1000
mi_units: 512
margin: 3
base_classifier: resnet18

resnet18:
  last_conv_channel: 512

resnet34:
  last_conv_channel: 512

resnet50:
  last_conv_channel: 2048

# training parameters
n_batch_train: 256
n_batch_test: 500
optimizer: adam
lr: 0.001
training_iters: 100000
log_interval: 2000
seed: 1234
n_gpu: 1
device: cuda

# working directories
log_dir: logs
data_dir: data


